# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=b'documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('roundsPlayed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('mvps', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('steamId', models.IntegerField(default=0)),
                ('isBot', models.BooleanField(default=False)),
                ('roundsPlayed', models.IntegerField(default=0)),
                ('roundsWon', models.IntegerField(default=0)),
                ('gamesPlayed', models.IntegerField(default=0)),
                ('gamesWon', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundsWon', models.IntegerField(default=0)),
                ('won', models.BooleanField(default=False)),
                ('playerFive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerFive', to='inHouseSite.Player')),
                ('playerFour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerFour', to='inHouseSite.Player')),
                ('playerOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerOne', to='inHouseSite.Player')),
                ('playerThree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerThree', to='inHouseSite.Player')),
                ('playerTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerTwo', to='inHouseSite.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='teamOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamOne', to='inHouseSite.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='teamTwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamTwo', to='inHouseSite.Team'),
        ),
    ]
