# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inHouseSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='steamId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
