# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inHouseSite', '0002_auto_20171229_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='steamId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
