# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inHouseSite', '0003_auto_20171229_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='isBot',
        ),
    ]
