# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inHouseSite', '0008_auto_20180118_1601'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='GameModel',
        ),
    ]
