# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inHouseSite', '0009_auto_20180118_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='playerFive',
        ),
        migrations.RemoveField(
            model_name='team',
            name='playerFour',
        ),
        migrations.RemoveField(
            model_name='team',
            name='playerOne',
        ),
        migrations.RemoveField(
            model_name='team',
            name='playerThree',
        ),
        migrations.RemoveField(
            model_name='team',
            name='playerTwo',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='roundsPlayed',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='teamOne',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='teamTwo',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='playerEight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerEight', to='inHouseSite.Player'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='playerFive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerFive', to='inHouseSite.Player'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='playerFour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerFour', to='inHouseSite.Player'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='playerNine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerNine', to='inHouseSite.Player'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='playerOne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerOne', to='inHouseSite.Player'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='playerSeven',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerSeven', to='inHouseSite.Player'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='playerSix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerSix', to='inHouseSite.Player'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='playerTen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerTen', to='inHouseSite.Player'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='playerThree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerThree', to='inHouseSite.Player'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='playerTwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerTwo', to='inHouseSite.Player'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='teamOneScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='teamTwoScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='map',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
