# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inHouseSite', '0011_auto_20180124_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallPlayer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('mvps', models.IntegerField(default=0)),
                ('steamId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('roundsPlayed', models.IntegerField(default=0)),
                ('roundsWon', models.IntegerField(default=0)),
                ('gamesPlayed', models.IntegerField(default=0)),
                ('gamesWon', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='gamesPlayed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gamesWon',
        ),
        migrations.RemoveField(
            model_name='player',
            name='roundsPlayed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='roundsWon',
        ),
    ]
