# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inHouseSite', '0012_auto_20180124_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gameNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='seasonNumber',
            field=models.IntegerField(default=0),
        ),
    ]
