# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inHouseSite', '0013_auto_20180124_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='teamNumber',
            field=models.IntegerField(default=0),
        ),
    ]
