# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inHouseSite', '0014_player_teamnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='playerEight',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='playerFive',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='playerFour',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='playerNine',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='playerOne',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='playerSeven',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='playerSix',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='playerTen',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='playerThree',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='playerTwo',
        ),
    ]
