# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inHouseSite', '0016_auto_20180124_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playerId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='steamId',
            field=models.CharField(max_length=30),
        ),
    ]
