# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inHouseSite', '0017_auto_20180124_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='playerId',
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
